<?php

namespace ContactBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\User;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends EntityRepository
{
    /**
     * @param $user User
     * @return array
     */
    public function findByUser(User $user) {
        $qb = $this->createQueryBuilder('g');

        $qb
            ->innerJoin('g.users', 'u')
            ->andWhere('u.id = ' . $user->getId())
        ;

        return $qb->getQuery()->getResult();
    }
}
