concierge:
   type: rest
   resource:    "APIRestBundle:RestUser"
   prefix: /
   name_prefix: "api_"

post:
   type: rest
   resource:    "APIRestBundle:RestPost"
   prefix: /
   name_prefix: "api_"



