nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /blog-api/doc

#app/routing_rest.yml
Rest_User :
  type : rest
  resource: "@APIRestBundle/Resources/config/routing_rest.yml"
  prefix: /api

contact:
    resource: "@ContactBundle/Controller/"
    type:     annotation
    prefix:   /contact

post:
    resource: "@PostBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"